### ISSUE TITLE
error when run demo

### ISSUE THREAD

**Issue by iwander-all** [Terminal-K/MambaMOS#2]
hello, type:
` sh scripts/test.sh -g 1 -d semantic_kitti -n mambamos -w model_best
`

it shows:
`Experiment name: mambamos
Python interpreter dir: python
Dataset: semantic_kitti
GPU Num: 1
Loading config in: exp/semantic_kitti/mambamos/config.py
Running code in: exp/semantic_kitti/mambamos/code
 =========> RUN TASK <=========
[2024-09-16 13:34:55,918 INFO test.py line 41 31324] => Loading config ...
[2024-09-16 13:34:55,918 INFO test.py line 48 31324] => Building model ...
[2024-09-16 13:34:56,270 INFO test.py line 61 31324] Num params: 49204647
[2024-09-16 13:34:57,842 INFO test.py line 68 31324] Loading weight at: exp/semantic_kitti/mambamos/model/model_best.pth
[2024-09-16 13:35:02,960 INFO test.py line 80 31324] => Loaded weight 'exp/semantic_kitti/mambamos/model/model_best.pth' (epoch 45)
[2024-09-16 13:35:02,960 INFO test.py line 53 31324] => Building test dataset & dataloader ...
Ground truth poses are not avaialble.
Traceback (most recent call last):
  File "/media/hunkyu/SuperBigDisk/DeepLearning/net/MOS/MambaMOS/pointcept/utils/registry.py", line 53, in build_from_cfg
    return obj_cls(**args)
  File "/media/hunkyu/SuperBigDisk/DeepLearning/net/MOS/MambaMOS/pointcept/datasets/semantic_kitti_multi_scans.py", line 95, in __init__
    super().__init__(
  File "/media/hunkyu/SuperBigDisk/DeepLearning/net/MOS/MambaMOS/pointcept/datasets/defaults.py", line 220, in __init__
    self.data_list = self.get_data_list()
  File "/media/hunkyu/SuperBigDisk/DeepLearning/net/MOS/MambaMOS/pointcept/datasets/semantic_kitti_multi_scans.py", line 171, in get_data_list
    self.poses[seq] = self.get_pose_data(pose_file=seq_pose_file, calib_file=seq_calib_file)
  File "/media/hunkyu/SuperBigDisk/DeepLearning/net/MOS/MambaMOS/pointcept/datasets/semantic_kitti_multi_scans.py", line 110, in get_pose_data
    inv_frame0 = np.linalg.inv(poses[0])
IndexError: index 0 is out of bounds for axis 0 with size 0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/media/hunkyu/SuperBigDisk/DeepLearning/net/MOS/MambaMOS/pointcept/utils/registry.py", line 53, in build_from_cfg
    return obj_cls(**args)
  File "/media/hunkyu/SuperBigDisk/DeepLearning/net/MOS/MambaMOS/pointcept/engines/test.py", line 54, in __init__
    self.test_loader = self.build_test_loader()
  File "/media/hunkyu/SuperBigDisk/DeepLearning/net/MOS/MambaMOS/pointcept/engines/test.py", line 90, in build_test_loader
    test_dataset = build_dataset(self.cfg.data.test)
  File "/media/hunkyu/SuperBigDisk/DeepLearning/net/MOS/MambaMOS/pointcept/datasets/builder.py", line 16, in build_dataset
    return DATASETS.build(cfg)
  File "/media/hunkyu/SuperBigDisk/DeepLearning/net/MOS/MambaMOS/pointcept/utils/registry.py", line 214, in build
    return self.build_func(*args, **kwargs, registry=self)
  File "/media/hunkyu/SuperBigDisk/DeepLearning/net/MOS/MambaMOS/pointcept/utils/registry.py", line 56, in build_from_cfg
    raise type(e)(f"{obj_cls.__name__}: {e}")
IndexError: SemanticKITTIMultiScansDataset: index 0 is out of bounds for axis 0 with size 0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tools/test.py", line 41, in <module>
    main()
  File "tools/test.py", line 30, in main
    launch(
  File "/media/hunkyu/SuperBigDisk/DeepLearning/net/MOS/MambaMOS/pointcept/engines/launch.py", line 89, in launch
    main_func(*cfg)
  File "tools/test.py", line 22, in main_worker
    tester = TESTERS.build(dict(type=cfg.test.type, cfg=cfg))
  File "/media/hunkyu/SuperBigDisk/DeepLearning/net/MOS/MambaMOS/pointcept/utils/registry.py", line 214, in build
    return self.build_func(*args, **kwargs, registry=self)
  File "/media/hunkyu/SuperBigDisk/DeepLearning/net/MOS/MambaMOS/pointcept/utils/registry.py", line 56, in build_from_cfg
    raise type(e)(f"{obj_cls.__name__}: {e}")
IndexError: SemSegTester: SemanticKITTIMultiScansDataset: index 0 is out of bounds for axis 0 with size 0
`

kitti data is organized as demo, how to solve it,, thanks

**Comment by Terminal-K** [comment]
Hi @iwander-all,
this seems to be a problem with the dataset path, please print and check the pose file path 'seq_pose_file' is correct.
https://github.com/Terminal-K/MambaMOS/blob/78370d0f022d0e6cb3a56d98342e7ae1014e440c/pointcept/datasets/semantic_kitti_multi_scans.py#L171

**Comment by iwander-all** [comment]
Wow, you are so juan as me that your answer is so fast. Thanks! My link to data is wrong
